name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Create matrix
      id: create_matrix
      run: |
        MATRIX_JSON=$(jq -r '. | to_entries | map({(.key): .value}) | .[]' inputs.json)
        echo "::set-output name=matrix::${MATRIX_JSON}"

  job1:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.APPLICATION_NAME }}
    - run: echo ${{ matrix.CONNECTOR_TYPE }}



    # ... and so on for the other variables  # job1:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   steps:
  #   - id: set-matrix
  #     # run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  #     run: echo "::set-output name=matrix::{\"include\":[{\"APPLICATION_NAME\":\"blahhh\",\"CONNECTOR_TYPE\":\"postgres\",\"DB_HOST\":\"FXIAZNEU\",\"DB_LOGIN_ID\":\"sqladmin\",\"DB_NAME\":\"blahhh\",\"DB_PASSWORD\":\"Password\",\"DB_PORT\":5436,\"EAI\":\"2314455\",\"INVENTORY_DB_HOST\":\"10.23.23.99\",\"INVENTORY_DB_NAME\":\"masking_inventory\",\"INVENTORY_DB_PASSWORD\":\"Password1\",\"INVENTORY_DB_PORT\":\"5435\",\"INVENTORY_DB_USER\":\"sqladmin\",\"MASKING_ENGINE_PASSWORD\":\"PASSWORD\",\"MASKING_ENGINE_USER\":\"masking-user-10-35-12-158\",\"POSTGRES_DB\":\"fsdfs\",\"POSTGRES_PORT\":5436,\"SCHEMA_NAME\":\"public\"},{\"APPLICATION_NAME\":\"blahhh\",\"CONNECTOR_TYPE\":\"postgres\",\"DB_HOST\":\"FXIAZNEU\",\"DB_LOGIN_ID\":\"sqladmin\",\"DB_NAME\":\"blahhh\",\"DB_PASSWORD\":\"Password\",\"DB_PORT\":5436,\"EAI\":\"2314455\",\"INVENTORY_DB_HOST\":\"10.23.23.99\",\"INVENTORY_DB_NAME\":\"masking_inventory\",\"INVENTORY_DB_PASSWORD\":\"Password1\",\"INVENTORY_DB_PORT\":\"5435\",\"INVENTORY_DB_USER\":\"sqladmin\",\"MASKING_ENGINE_PASSWORD\":\"PASSWORD\",\"MASKING_ENGINE_USER\":\"masking-user-10-35-12-158\",\"POSTGRES_DB\":\"blahhh\",\"POSTGRES_PORT\":5438,\"SCHEMA_NAME\":\"public\"}]}"
  # job2:
  #   needs: job1
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix: ${{fromJson(needs.job1.outputs.matrix)}}
  #   steps:
  #   - run: echo ${{ matrix.APPLICATION_NAME }}
  #   - run: echo ${{ matrix.CONNECTOR_TYPE }}
  #   - run: echo ${{ matrix.DB_HOST }}
  #   - run: echo ${{ matrix.DB_LOGIN_ID }}
  #   - run: echo ${{ matrix.DB_NAME }}
  #   - run: echo ${{ matrix.DB_PASSWORD }}
  #   - run: echo ${{ matrix.DB_PORT }}
  #   - run: echo ${{ matrix.EAI }}
  #   - run: echo ${{ matrix.INVENTORY_DB_HOST }}
  #   - run: echo ${{ matrix.INVENTORY_DB_NAME }}
  #   - run: echo ${{ matrix.INVENTORY_DB_PASSWORD }}
  #   - run: echo ${{ matrix.INVENTORY_DB_PORT }}
  #   - run: echo ${{ matrix.INVENTORY_DB_USER }}
  #   - run: echo ${{ matrix.MASKING_ENGINE_PASSWORD }}
  #   - run: echo ${{ matrix.MASKING_ENGINE_URL }}
  #   - run: echo ${{ matrix.MASKING_ENGINE_USER }}
  #   - run: echo ${{ matrix.POSTGRES_DB }}
  #   - run: echo ${{ matrix.POSTGRES_PORT }}
  #   - run: echo ${{ matrix.SCHEMA_NAME }}
