name: Profile

on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi
        run: echo "This is the profile job"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run Script
        run: |
          pwd
          python ./scripts/my_script.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Temp-File
          path: |
            ./scripts/myfile.txt
