name: Greet

on:
  push:
    branches: ["feature/workflow"]
  pull_request:
    branches: ["feature/workflow"]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi
        run: echo "Hi from start"
