name: Profile

on:
  workflow_call:
    secrets:
      PAT:
        required: true

env:
  MASKING_REPO: mjspeller/tempwf

jobs:
  profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MASKING_REPO }}
          ref: main
          token: ${{ secrets.PAT }}
      - name: Profile
        run: echo "This is the profile job"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run Script
        run: |
          pwd
          ls -la
          cat README.md
          cd ..
          ls -la
          cd ..
          ls -la
          # python scripts/my_script.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Temp-File
          path: |
            scripts/myfile.txt
